import "./globals.css";

import React, { FC } from "react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

interface Props {
  children: React.ReactNode;
}

const RootLayout: FC<Props> = (props) => {
  const { children } = props;

  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
};

export default RootLayout;
